sonar.projectKey=AparnaMounikau763_test
sonar.organization=aparnamounikau763

sonar.sources=.
sonar.tests=tests

sonar.test.inclusions=tests/**/*.py

sonar.python.version=3.12
sonar.python.coverage.reportPaths=coverage.xml

sonar.exclusions=.github/**,Dockerfile